### PR TITLE
Added apparmor profiles for light-locker and light-locker-command

### PR DESCRIPTION
**Pull request by CameronNemo**

### CODE REVIEW

**Comment by cavalier38** [comment]
Could you give me a link to other projects with app armor files, so I do a better review of this?

**Comment by CameronNemo** [comment]
I can point you to https://code.launchpad.net/apparmor-profiles which is a repository full of apparmor profiles. Also you can ask the mailing list (apparmor@lists.ubuntu.com) for a review.

Anyway, here are two individual projects which ship apparmor profiles:

https://github.com/cjdelisle/cjdns (in contrib/apparmor)

https://github.com/jedisct1/dnscrypt-proxy (at ./apparmor.profile.dnscrypt-proxy)

**Comment by cavalier38** [comment]
I like the Makefile to be explicit. So I don't want to include a direcotry in EXTRA_DIST.
I move the files to the data directory and explicitly listed them. see the apparmor branch.
Is this ok, or would it be easier for distributions to have an apparmor exclusive directory (so they can install all the content)?
Or I could add a --with-apparmor flag to specify the apparmor install direcotry (/etc/apparmor.d)?

**Comment by CameronNemo** [comment]
Looks great as is. :+1:

**Pull request merged**
